#!/bin/zsh

mv ~/.gitconfig.user{,.backup}
mv ~/.pentadactyl{,.backup}
mv ~/.pentadactylrc{,.backup}
mv ~/.tmux.conf.user{,.backup}
mv ~/.zprofile{,.backup}

PWD=`pwd`

ln -s $PWD/.gitconfig.user ~
ln -s $PWD/.pentadactyl ~
ln -s $PWD/.pentadactylrc ~
ln -s $PWD/.tmux.conf.user ~
ln -s $PWD/.zprofile ~
